const fishEntry = [
  {
    x: 400,
    y: 100,
    majorAxis: 20,
    minorAxis: 10,
    dx: 4,
    dy: 0,
    color: "#0A5EB0",
    originalColor:"#0A5EB0",
    waveOffset: 0,
    rotate: 0 * (Math.PI / 180),
    speed: 2,
    headX: 100,
    headY: 100,
  },
  {
    x: 100,
    y: 100,
    majorAxis: 20,
    minorAxis: 15,
    dx: 4,
    dy: 0,
    color: "gray",
    originalColor:"gray",
    waveOffset: 0,
    rotate: 0 * (Math.PI / 180),
    speed: 1,
    headX: 100,
    headY: 100,
  },
  {
    x: 500,
    y: 400,
    majorAxis: 15,
    minorAxis: 8,
    dx: 4,
    dy: 0,
    color: "green",
    originalColor:"green",
    waveOffset: 0,
    rotate: 0 * (Math.PI / 180),
    speed: 2,
    headX: 100,
    headY: 100,
  },
  {
    x: 200,
    y: 110,
    majorAxis: 20,
    minorAxis: 10,
    dx: 4,
    dy: 0,
    color: "ghostwhite",
    originalColor: "ghostwhite",
    waveOffset: 0,
    rotate: 0 * (Math.PI / 180),
    speed: 1,
    headX: 100,
    headY: 100,
  },
  {
    x: 200,
    y: 110,
    majorAxis: 20,
    minorAxis: 10,
    dx: 4,
    dy: 0,
    color: "violet",
    originalColor:"violet",
    waveOffset: 0,
    rotate: 0 * (Math.PI / 180),
    speed: 1,
    headX: 100,
    headY: 100,
  },
  {
    x: 150,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 25,
    minorAxis: 12,
    dx: 3,
    dy: 0,
    color: "blue",
    originalColor: "blue",
    waveOffset: 1,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.5,
    headX: 100,
    headY: 90,
  },
  {
    x: 220,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 30,
    minorAxis: 15,
    dx: 4,
    dy: 0,
    color: "red",
    originalColor:"red",
    waveOffset: 0.5,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 2,
    headX: 120,
    headY: 120,
  },
  {
    x: 100,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 18,
    minorAxis: 9,
    dx: 2,
    dy: 0,
    color: "yellow",
    originalColor:"yellow",
    waveOffset: 0.2,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 0.8,
    headX: 90,
    headY: 70,
  },
  {
    x: 300,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 20,
    minorAxis: 10,
    dx: 5,
    dy: 0,
    color: "green",
    originalColor:"green",
    waveOffset: 1.2,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.3,
    headX: 110,
    headY: 85,
  },
  {
    x: 180,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 28,
    minorAxis: 14,
    dx: 3,
    dy: 0,
    color: "orange",
    originalColor: "orange",
    waveOffset: 0.8,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.7,
    headX: 105,
    headY: 95,
  },
  {
    x: 90,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 22,
    minorAxis: 11,
    dx: 2.5,
    dy: 0,
    color: "purple",
    originalColor:"purple",
    waveOffset: 0.4,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1,
    headX: 95,
    headY: 60,
  },
  {
    x: 250,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 26,
    minorAxis: 13,
    dx: 4.5,
    dy: 0,
    color: "cyan",
    originalColor:"cyan",
    waveOffset: 1.5,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.9,
    headX: 130,
    headY: 110,
  },
  {
    x: 320,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 24,
    minorAxis: 12,
    dx: 3.5,
    dy: 0,
    color: "pink",
    originalColor: "pink",
    waveOffset: 0.7,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.2,
    headX: 115,
    headY: 100,
  },
  {
    x: 70,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 21,
    minorAxis: 10,
    dx: 2.8,
    dy: 0,
    color: "lime",
    originalColor: "lime",
    waveOffset: 0.9,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.1,
    headX: 88,
    headY: 75,
  },
  {
    x: 200,
    y: Math.random() * window.innerHeight, // Random height within the canvas
    majorAxis: 19,
    minorAxis: 9,
    dx: 3.2,
    dy: 0,
    color: "teal",
    originalColor: "teal",
    waveOffset: 0.3,
    rotate: 0 * (Math.PI / 180), // Initial angle is zero
    speed: 1.4,
    headX: 102,
    headY: 87,
  },
];

export { fishEntry };
